wds/core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import home, Trade, reqcreate,received_request,sent_request,accept_request,decline_request,cancel_request,report,history,all_history
from core import views
app_name="core"

urlpatterns = [
    
    path('register/',views.register,name='register'),
    path('userlogin/',views.user_login,name='userlogin'),
    path('stocks/',views.stock_display,name='stocks'),
    path('userlogout/',views.userlogout,name='userlogout'),
    path('news/',views.news,name='news'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('report/',report,name='report'),
    path('buy-sell-form/',Trade.as_view(),name='buy-sell-form'),
    path('reqcreate/',reqcreate,name='createrequest'),
    path('receivedreq/',received_request,name='receivedreq'),
    path('sentreq/',sent_request,name='sentreq'),
    path('report/',report,name='report'),
    path('transaction-history/',history,name='transaction-history'),
    path('transaction-log/',all_history,name='transaction-log'),
    path('accept_request/<friend_request_id>',accept_request,name='accept-request'),
    path('decline_request/<friend_request_id>',decline_request,name='decline-request'),
    path('cancel_request/<friend_request_id>',cancel_request,name='cancel-request'),
    path('',home,name="home"),
    
]

wds/wds/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('register/', core_views.register, name='register'),
    path('',include('core.urls',namespace='core')),
    #path('',include('international.urls',namespace='international'))
    #path('',include('tradingclosed.urls',namespace='tradingclosed')),
]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

wds/templates/buy-sell-form.html
{% load static %}
{% load crispy_forms_tags %}
{% block content %}


<div>
    <h1>Fill the form to buy/sell stocks!</h1>
    <form method='POST' enctype="\application/x-www-form-urlencoded">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-outline-info">Submit</button>
    </form>
</div>



{% endblock %}

wds/templates/navbar.html
{% load static %}
<head>
    <style>
        nav.fixed .logo-dark, .fixed nav .logo-dark {
    display: block;
    width: 100px;
    top: 10px;
}
.top-nav a {
        font-family: 'Spectral SC', serif;
    }

    </style>
</head>
        <nav class="background-transparent background-dark-dott full-width sticky">
            <!-- mobile version logo -->
            <div class="logo hide-l hide-xl hide-xxl">
                <a href="index.html" class="logo">
                    <!-- Logo Dark Version -->
                    <img class="logo-dark" src="{% static 'images-2019/WDS_Logo_Black.png'%}" alt="">
                </a>
            </div>
            <div class="top-nav">

                <!-- left menu items -->
                <div class="top-nav left-menu">
                    <ul class="right top-ul chevron">
                        <li class="active-item">
                            
                            {% csrf_token %}
                            {% if user.is_staff %}
                            <a href="{% url 'admin:index' %}">&nbsp Admin </a>
                            {% endif %}
                        </li>

                            <li>

                            <a href="{% url 'core:home' %}">Home</a>
                            {% comment  %}
                            <a href="{% url 'international:home' %}">Home</a>
                            {% endcomment %}
                        </li>
                        <li>
                        
                        <a href="{% url 'core:stocks' %}">&nbsp Stocks</a>
                        
                        </li>
                        
                        
                        
                       
                    </ul>
                </div>

                <!-- logo -->
                <ul class="logo-menu">
                    
                <a href="{% url 'core:home' %}" class="logo">
                {% comment  %}
                <a href="{% url 'international:home' %}" class="logo"></a>
                {% endcomment %}
                        <!-- Logo White Version -->
                        <img class="logo-white" src="{% static 'images-2019/WDS_Logo_Black_3.png'%}" alt="">
                        <!-- Logo Dark Version -->
                        <img class="logo-dark" src="{% static 'images-2019/WDS_Logo_Black_3.png'%}" alt="">
                        
                    </a>
                </ul>
                
                <!-- right menu items -->
                <div class="top-nav right-menu">
                    <ul class="top-ul chevron">
                        
                        {% if user.is_authenticated %}
                        
                        <li><a href="{% url 'core:dashboard' %}">&nbsp Dashboard</a></li>
                        <li><a href="{% url 'core:userlogout' %}">&nbsp Logout</a></li>
                        {% else %}
                        
                        <li><a href="{% url 'core:userlogin' %}">&nbsp Login</a></li>
                        <li><a href="{%url 'core:register' %}">&nbsp Register</a></li>
                        {% endif %}
                        
                        
                                        
                    </ul>
                </div>
            </div>
        </nav>
        

wds/templates/received_request.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<html>
	
	<head>
		<style>
        
            
			*{
				margin: 0; padding: 0;
				box-sizing: border-box;
			}
	
			body{
				background: #00000f;
				text-transform: capitalize;
			}
			.main-page{
				display: flex;
				height: 100%;
			}
	
				
		/*   ---------------------------    SIDE BAR   -------------------------------- */
		.side-bar-wrapper {
			width: 17vw;
			/* height: 95vh; */
			margin: 5vh 0;
			color: #FCAF58;
			padding: 0 10px 0 0px;
			border-right: 2px solid white;
			
		}
		
		/*   -------------- team info  ------------- */
		
		.side-bar-wrapper .team-info{
			/* background: #212646; */
			text-align: center;
			margin: 10px;
			padding: 5px 10px 20px 10px;
			border-radius: 30px;
			/* box-shadow: 3px 3px 15px 0 #212646; */
			box-shadow: 1px 1px 15px 0 #00000f;
			
			
		}
		.side-bar-wrapper .team-info .team-name h2{             /*  name size */
			font-size: 2rem;
			font-weight: bolder;
			margin-bottom: 25px;
			color: #FCAF58;
			font-family: 'Sanchez', serif;
			text-transform: uppercase;
		}
	
		
		
		
		/*   ---------------- Buttons  -------------- */
		.requestButtons{
			margin-top: 30px;
		}
		.requestButtons .req-btn{
			margin-bottom: 10px;
			display: flex;
			flex-flow: column;
		}
		.requestButtons .req-btn  {
			margin-left: 10px;
			border-bottom: 1.5px solid #212646;
			text-align: center;                     /* links to center */
		}
		.requestButtons .req-btn:hover{
			cursor: pointer;
			text-align: center;               
		}
		.requestButtons .req-btn a{
			font-size: 0.9rem;
			text-transform: uppercase;
			padding: 15px 10px;
			color: whitesmoke;
		
		}
		.requestButtons .req-btn a:hover{
			text-align: center;               /* links to center on hovering */
		}
		
	
	
			/*  ------------------------ TABLE ------------------------  */
	
		th, table tr:nth-of-type(2n){
		  border: none;
		  background: transparent;
	  }
	  
	  th, table tr:nth-of-type(2n) td{
		  border: none;
		  background: transparent;
	  }
	
			/* ---------- table section ---------- */
		.table-section{
			width: 70vw;
			height: 60vmin;
			display: flex;
			flex-flow: column;
			margin: 5vh auto;
			
		}
			/* ---------- table heading ---------- */
		.table-section h1{
			text-transform: capitalize;
			margin-bottom: 20px;
			text-align: center;
			font-size: 2rem;
			font-weight: 500;
			color: #FCAF58;
		}
	
			/* -------------- table -------------- */
		.table-section table{
			border: none;
			background: #8953b036;
			width: 100%;
		}
	
		.table-section table thead {
		  height: 70px;
		  background: none;
		  border: none;
		  background-image: linear-gradient(to right, #46317796, #29718398);
		  border-bottom: 2px solid #fff;
		}
	
		.table-section thead th{
		  font-size: 1.2rem;
		  text-align: center;
		  height: 50px;
		  z-index: 10;
		  color: white;
	  }
	
	  .table-section tbody td{
		  text-align: center;
		  font-size: 1.3rem;
		  margin-right: 1px;
		  padding-right: 10px;
		  color: white;
		  z-index: 10;
		  text-transform: capitalize;
	  }
		.accept-request a, .decline-request a {
			color: #f8bd95;
		}
		.accept-request a:hover{
			color: #00b045;
		}
		.decline-request a:hover{
			color: red;
		}

		.table-message p{
			font-size: 1rem;
			color: white;
			margin-top: 20px;
			margin-left: 10px;
		}





    /* ----------------- side bar accordian ----------------- */
	.side-bar-caret{
  display: none;
  font-size: 30px;
  color: #FCAF58;
}


.card, .card-body{
  padding: 0;
}
.side-bar-wrapper-acc {
      width: 100%;
      color: #FCAF58;
      background: #000;
  }
  .team-info-acc{
    display: none;
  }

.side-bar-wrapper-acc{
      background: #000000;
      text-align: center;
      width: 100vw;
      padding: 5px 10px 20px 0px;
}

  .team-info-acc .team-name h2{             /*  name size */
      font-size: 2rem;
      font-weight: bolder;
      margin-bottom: 25px;
      color: #FCAF58;
      font-family: 'Sanchez', serif;
      text-transform: uppercase;
      text-align: center;
  }
  .team-info-acc .team-balance h5 {
      font-size: 1.1em;
      color:  #f5a976;
      line-height: 1.5rem;
      margin: 0 10%;
      text-align: center;
      font-family: 'Sanchez', serif;
  }
  .req-btn a{
    color: #fff;
  }
  


  
  @media (max-width: 720px) {

    .main-page{
      display: block;
	  height: 110vh;
	  width: 100vw;
    }
    .side-bar-wrapper{
      display: none;
    }
    .team-info-acc{
      display: block;
    }


    .side-bar-caret{
      display: flex;
      width: 20%;
      justify-content: center;
      align-items: center;
    }
    .stock-table{
      margin: 0 auto;
    }
    .stockTableInsider thead th{
      font-size: 1rem;
      width: 90%;
    }
    .stockTableInsider tbody td{
      font-size: 0.8rem;
    }

	.table-section{
		width: 100%;
		height: 100%;
		display: flex;
		margin: 10px 5px;
		text-align: center;
	}
	.table-section h1{
		margin-top: 30px;
	}
	.table-section .table-message{
		margin: 0 auto;
		width: 70%;
	}
	table{
		margin: 0 10% 10% 10% 10%;
	}
    .table-section thead th {
		font-size: 0.7rem;
		text-align: center;
		height: 30px;
		color: white;
	
	}


  


  }










	</style>
	</head>

	<body>

	<section class="main-page">
	
		

<!-- ---------------------------- accordian ---------------------------- -->
<div class="team-info-acc">
	<div class="team-name"><h2>{{ user.username }}</h2></div>
	<div class="team-balance">    
	  {% for dd in dashdata %}
	  <h5>Team Balance {{ dd.userbalance }}</h5>
	  {% endfor %}
	</div>
  </div>


	<a class="side-bar-caret" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
	  <i class="fa fa-angle-down" style="color: #FCAF58;"></i>
	</a>
	
  <div class="collapse" id="collapseExample">

	  <div class="side-bar-wrapper-acc">

		<div class="requestButtons">
                
			<div class="req-btn"><a class="btn-insider" href="{% url 'core:dashboard' %}">Dashboard</a></div>
			<div class="req-btn"><a class="btn-insider" href="{% url 'core:stocks' %}">Stock Market</a></div>
			<div class="req-btn"><a class="btn-insider" href="{% url 'core:createrequest' %}">Create Trade Request</a></div>
			<div class="req-btn"><a class="btn-insider" href="{% url 'core:sentreq' %}">Requests Sent</a></div>
			<div class="req-btn"><a class="btn-insider" href="{% url 'core:receivedreq' %}" style="color:#f8bd95">Received Requests</a></div>
			<div class="req-btn"><a class="btn-insider" href="{% url 'core:transaction-history' %}">Sent Requests Status</a></div>
			<div class="req-btn"><a class="btn-insider" href="{% url 'core:transaction-log' %}">Transactions</a></div>
			<div class="req-btn"><a class="btn-insider" href="{% url 'core:report' %}">Report(Insider Trading)</a></div>
			
			<div class="req-btn"><a class="btn-insider" href="https://unh.zoom.us/j/95053387491?pwd=aTZ6d0xUOGlSTXBwQUxBVWJ6WHBudz09">Insider Trading</a></div>
		</div>
	  
  </div>

  </div>







		<div class="side-bar-wrapper">
            
                <div class="team-info">
                <div class="team-name"><h2>{{ user.username }}</h2></div>
                <div class="team-balance">    
                    {% for dd in dashdata %}
                    <h5>Team Balance {{ dd.userbalance }}</h5>
                    {% endfor %}
                </div>
                </div>

                <div class="requestButtons">
                
				<div class="req-btn"><a class="btn-insider" href="{% url 'core:dashboard' %}">Dashboard</a></div>
				<div class="req-btn"><a class="btn-insider" href="{% url 'core:stocks' %}">Stock Market</a></div>
                <div class="req-btn"><a class="btn-insider" href="{% url 'core:createrequest' %}">Create Trade Request</a></div>
                <div class="req-btn"><a class="btn-insider" href="{% url 'core:sentreq' %}">Requests Sent</a></div>
                <div class="req-btn"><a class="btn-insider" href="{% url 'core:receivedreq' %}" style="color:#f8bd95">Received Requests</a></div>
                <div class="req-btn"><a class="btn-insider" href="{% url 'core:transaction-history' %}">Sent Requests Status</a></div>
                <div class="req-btn"><a class="btn-insider" href="{% url 'core:transaction-log' %}">Transactions</a></div>
                <div class="req-btn"><a class="btn-insider" href="{% url 'core:report' %}">Report (Insider Trading)</a></div>
                
                <div class="req-btn"><a class="btn-insider" href="https://unh.zoom.us/j/95053387491?pwd=aTZ6d0xUOGlSTXBwQUxBVWJ6WHBudz09">Insider Trading</a></div>
            </div>
            
        </div>

		<div class="table-section">
			<h1>received requests </h1>

			<div class="table-message">
				<p>*If type is sell that means you are the buyer and if the type is buy then you are the seller.</p>
			</div>
			<table>
				<thead>
				<tr>
					<th>sender</th>
					<th>type</th>
					<th>stock</th>
					<th>number of stocks</th>
					<th>priceperstock</th>
					<th>accept</th>
					<th>delete</th>
				</tr>
				</thead>

			{% for req in requests %}
			<tbody>
				<tr>
					<td>{{ req.sender }}</td>
					<td>{{ req.action }} </td>
					<td>{{ req.stock }} </td>
					<td>{{ req.numberofstocks }}</td>
					<td>{{ req.priceperstock }}</td>

					<td class="accept-request"><a href="{% url 'core:accept-request' req.id %}">accept</a></td>
					<td class="decline-request"><a href="{% url 'core:decline-request' req.id %}">decline</a></td>
					{% comment  %}
					<td class="accept-request"><a href="{% url 'international:accept-request' req.id %}">accept</a></td>
					<td class="decline-request"><a href="{% url 'international:decline-request' req.id %}">decline</a></td>
					{% endcomment %}
				</tr>
				{% endfor %}
			</tbody>

			</table>
		</div>

	</section>

	<script type="text/javascript">
		function onFriendRequestAccepted(){
			location.reload();
		}

		function onFriendRequestDeclined(){
			location.reload();
		}

		function triggerAcceptFriendRequest(friend_request_id){
			acceptFriendRequest(friend_request_id, onFriendRequestAccepted)
		}

		function triggerDeclineFriendRequest(friend_request_id){
			declineFriendRequest(friend_request_id, onFriendRequestDeclined)
		}
		
		
	</script>
	</body>
</html>
{% endblock %}

wds/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block regis %}


<style>
  @import url('http://fonts.googleapis.com/css?family=Open+Sans:400,700');
*{
	padding:0;
	margin:0;
}

body{
    background-image: url("{% static 'images-2019/bg-11.jpg' %}");
    background-attachment: fixed;
    background-position: center;
    background-repeat: no-repeat;
	background-size: cover;
    font:16px/1.6 Arial,  sans-serif;
}

.background-transparent {
    background: none;
    border: none;
    box-shadow: none;
}

.top-nav ul li a{
    color: #fff;
    font-size: 1.35rem;
}
.form-field{
  height:3.5rem !important;
}
.btn {
  background-color: #FCAF58;
}
.main-form{
  box-shadow: 2px 10px 40px rgba(224, 137, 74,0.5);
}
.form-heading{
    text-align: center;
    width: 100%;
}
.form-heading h2{
  font-size: 2.5rem;
  font-family: 'Spectral SC', serif;
}

form button{
      color: black;
      padding: 10px 25px;
      text-transform: uppercase;
      border-radius: 15px;
      border: none;
      background:#FCAF58;
  }
  form button:hover{
      background: #fcaf58bb;
  }
  form button:active{
      background: #FCAF58;
      
  }

</style>
<body>
    <!-- HEADER -->
    <header role="banner" class="position-absolute">
  {% include "navbar.html" %}

    </header>
  <section>

    <div class="container-fluid col-xl-5" style="padding:7px; ">
      <div class="row main-form">
          <div class="form-heading">
              <h2>Register</h2>
          </div>
     
         <form class="col s12" method="POST">
            {% csrf_token %}
          <div class="row">
              <div class="input-field col s12 form-field">
                  <input  id="first_name" type="text" class="validate form-field"  name="username">
                  <label for="Username">User Name</label>
              </div>
          </div>
          <div class="row">
            <div class="input-field col s12 form-field">
                <input  id="email" type="email" class="validate form-field"  name="email">
                <label for="email">Email</label>
            </div>
        </div>
          <div class="row">
              <div class="input-field col s12 form-field">
                  <input id="password" type="password" class="validate form-field" name="password">
                  <label for="Password">Password</label>
              </div>
          </div>      
          <button class="" type="submit" name="action">Register
              <i class="material-icons right"></i>
          </button>
          </form>
      </div>
    </div>
  </section>
</body>
{% endblock %}

wds/templates/sell-form.html
{% load static %}
{% load crispy_forms_tags %}
{% block content %}


<div>
    <h1>Fill the form to buy/sell stocks!</h1>
    <form method='POST' enctype="\application/x-www-form-urlencoded">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-outline-info" id="id_send_sell_request_btn">Send Request</button>
    </form>
</div>



{% endblock %}

wds/templates/sent_requests.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <head>
        <style>
            
        *{
            margin: 0; padding: 0;
            box-sizing: border-box;
        }

        body{
            background: #00000f;
        }
        .main-page{
            display: flex;
            height: 100%;

        }

            
    /*   ---------------------------    SIDE BAR   -------------------------------- */
    .side-bar-wrapper {
        width: 17vw;
        /* height: 95vh; */
        margin: 5vh 0;
        color: #FCAF58;
        padding: 0 10px 0 0px;
        border-right: 2px solid white;   
    }
    
    /*   -------------- team info  ------------- */
    
    .side-bar-wrapper .team-info{
        /* background: #212646; */
        text-align: center;
        margin: 10px;
        padding: 5px 10px 20px 10px;
        border-radius: 30px;
        /* box-shadow: 3px 3px 15px 0 #212646; */
        box-shadow: 1px 1px 15px 0 #00000f;
        
        
    }
    .side-bar-wrapper .team-info .team-name h2{             /*  name size */
        font-size: 2rem;
        font-weight: bolder;
        margin-bottom: 25px;
        color: #FCAF58;
        font-family: 'Sanchez', serif;
        text-transform: uppercase;
    }

    
    
    
    /*   ---------------- Buttons  -------------- */
    .requestButtons{
        margin-top: 30px;
    }
    .requestButtons .req-btn{
        margin-bottom: 10px;
        display: flex;
        flex-flow: column;
    }
    .requestButtons .req-btn  {
        margin-left: 10px;
        border-bottom: 1.5px solid #212646;
        text-align: center;                     /* links to center */
    }
    .requestButtons .req-btn:hover{
        cursor: pointer;
        text-align: center;               
    }
    .requestButtons .req-btn a{
        font-size: 0.9rem;
        text-transform: uppercase;
        padding: 15px 10px;
        color: whitesmoke;
    
    }
    .requestButtons .req-btn a:hover{
        text-align: center;               /* links to center on hovering */
    }
    


        /*  ------------------------ TABLE ------------------------  */

    th, table tr:nth-of-type(2n){
      border: none;
      background: transparent;
  }
  
  th, table tr:nth-of-type(2n) td{
      border: none;
      background: transparent;
  }

        /* ---------- table section ---------- */
    .table-section{
        width: 70vw;
        height: 60vmin;
        display: flex;
        flex-flow: column;
        margin: 5vh auto;
        
    }
        /* ---------- table heading ---------- */
    .table-section h1{
        text-transform: capitalize;
        margin-bottom: 20px;
        text-align: center;
        font-size: 2rem;
        font-weight: 500;
        color: #FCAF58;
    }

        /* -------------- table -------------- */
    .table-section table{
        border: none;
        background: #8953b036;
        width: 100%;
    }

    .table-section table thead {
      height: 70px;
      background: none;
      border: none;
      background-image: linear-gradient(to right, #46317796, #29718398);
      border-bottom: 2px solid #fff;
    }

    .table-section thead th{
      font-size: 1.2rem;
      text-align: center;
      height: 50px;
      z-index: 10;
      color: white;
  }

  .table-section tbody td{
      text-align: center;
      font-size: 1.3rem;
      margin-right: 1px;
      padding-right: 10px;
      color: white;
      z-index: 10;
      text-transform: capitalize;
  }
    .cancel-button a {
        color: #f8bd95;
    }
    .cancel-button a:hover{
        color: red;
    }





    /* ----------------- side bar accordian ----------------- */
.side-bar-caret{
  display: none;
  font-size: 30px;
  color: #FCAF58;
}


.card, .card-body{
  padding: 0;
}
.side-bar-wrapper-acc {
      width: 100%;
      color: #FCAF58;
      background: #000;
  }
  .team-info-acc{
    display: none;
  }

.side-bar-wrapper-acc{
      background: #000000;
      text-align: center;
      width: 100vw;
      padding: 5px 10px 20px 0px;
}

  .team-info-acc .team-name h2{             /*  name size */
      font-size: 2rem;
      font-weight: bolder;
      margin-bottom: 25px;
      color: #FCAF58;
      font-family: 'Sanchez', serif;
      text-transform: uppercase;
      text-align: center;
  }
  .team-info-acc .team-balance h5 {
      font-size: 1.1em;
      color:  #f5a976;
      line-height: 1.5rem;
      margin: 0 10%;
      text-align: center;
      font-family: 'Sanchez', serif;
  }
  .req-btn a{
    color: #fff;
  }
  


  
  @media (max-width: 720px) {

.main-page{
  display: block;
height: 110vh;
}
.side-bar-wrapper{
  display: none;
}
.team-info-acc{
  display: block;
}


.side-bar-caret{
  display: flex;
  width: 20%;
  justify-content: center;
  align-items: center;
}
.stock-table{
  margin: 0 auto;
}
.stockTableInsider thead th{
  font-size: 1rem;
  width: 90%;
}
.stockTableInsider tbody td{
  font-size: 0.8rem;
}

.table-section{
width: 100%;
height: 100%;
display: flex;
margin: 10px 5px;
text-align: center;
}
.table-section h1{
margin-top: 30px;
}
.table-section .table-message{
margin: 0 auto;
width: 70%;
}
.table-section thead th {
font-size: 1rem;
text-align: center;
height: 30px;
color: white;

}





}





        </style>
    </head>


    <body>
        
    <section class="main-page">

<!-- ---------------------------- accordian ---------------------------- -->
        <div class="team-info-acc">
            <div class="team-name"><h2>{{ user.username }}</h2></div>
            <div class="team-balance">    
              {% for dd in dashdata %}
              <h5>Team Balance {{ dd.userbalance }}</h5>
              {% endfor %}
            </div>
          </div>
    
    
            <a class="side-bar-caret" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
              <i class="fa fa-angle-down" style="color: #FCAF58;"></i>
            </a>
            
          <div class="collapse" id="collapseExample">
            <div class="">
              <div class="side-bar-wrapper-acc">
    
                <div class="requestButtons">
                
                    <div class="req-btn"><a class="btn-insider" href="{% url 'core:dashboard' %}">Dashboard</a></div>
                    <div class="req-btn"><a class="btn-insider" href="{% url 'core:stocks' %}">Stock Market</a></div>
                    <div class="req-btn"><a class="btn-insider" href="{% url 'core:createrequest' %}">Create Trade Request</a></div>
                    <div class="req-btn"><a class="btn-insider" href="{% url 'core:sentreq' %}" style="color:#f8bd95">Requests Sent</a></div>
                    <div class="req-btn"><a class="btn-insider" href="{% url 'core:receivedreq' %}">Received Requests</a></div>
                    <div class="req-btn"><a class="btn-insider" href="{% url 'core:transaction-history' %}">Sent Requests Status</a></div>
                    <div class="req-btn"><a class="btn-insider" href="{% url 'core:transaction-log' %}">Transactions</a></div>
                    <div class="req-btn"><a class="btn-insider" href="{% url 'core:report' %}">Report(Insider Trading)</a></div>

                    
                    <div class="req-btn"><a class="btn-insider" href="https://unh.zoom.us/j/95053387491?pwd=aTZ6d0xUOGlSTXBwQUxBVWJ6WHBudz09">Insider Trading</a></div>
                </div>
              
          </div>
            </div>
          </div>





            <div class="side-bar-wrapper">
            
                <div class="team-info">
                <div class="team-name"><h2>{{ user.username }}</h2></div>
                <div class="team-balance">    
                    {% for dd in dashdata %}
                    <h5>Team Balance {{ dd.userbalance }}</h5>
                    {% endfor %}
                </div>
                </div>

                <div class="requestButtons">
                
                <div class="req-btn"><a class="btn-insider" href="{% url 'core:dashboard' %}">Dashboard</a></div>
                <div class="req-btn"><a class="btn-insider" href="{% url 'core:stocks' %}">Stock Market</a></div>
                <div class="req-btn"><a class="btn-insider" href="{% url 'core:createrequest' %}">Create Trade Request</a></div>
                <div class="req-btn"><a class="btn-insider" href="{% url 'core:sentreq' %}" style="color:#f8bd95">Requests Sent</a></div>
                <div class="req-btn"><a class="btn-insider" href="{% url 'core:receivedreq' %}">Received Requests</a></div>
                <div class="req-btn"><a class="btn-insider" href="{% url 'core:transaction-history' %}">Sent Requests Status</a></div>
                <div class="req-btn"><a class="btn-insider" href="{% url 'core:transaction-log' %}">Transactions</a></div>
                <div class="req-btn"><a class="btn-insider" href="{% url 'core:report' %}">Report (Insider Trading)</a></div>

                
                <div class="req-btn"><a class="btn-insider" href="https://unh.zoom.us/j/95053387491?pwd=aTZ6d0xUOGlSTXBwQUxBVWJ6WHBudz09">Insider Trading</a></div>
            </div>
            
        </div>
        
        <div class="table-section">

        <h1>waiting for confirmation from another user</h1>
            <table>
                <thead>
                <tr>
                    <th>Reciever</th>
                    <th>Type</th>
                    <th>Stock</th>
                    <th>Number of Stocks</th>
                    <th>Price Per Stock</th>
                    <th>Cancel Request</th>
                
                </tr>
                </thead>
                
                <tbody>
                    {% for req in requests %}
                <tr>
                    <td>{{ req.receiver }}</td>
                    <td>{{ req.action }} </td>
                    <td>{{ req.stock }} </td>
                    <td>{{ req.numberofstocks }}</td>
                    <td>{{ req.priceperstock }}</td>  
                    <td class="cancel-button"> <a href="{% url 'core:cancel-request' req.id %}">Cancel</a></td>
                    {% comment  %}
                    <td class="cancel-button"> <a href="{% url 'international:cancel-request' req.id %}">Cancel</a></td>
                    {% endcomment %} 
                    
                </tr>
                    {% endfor %}
                </tbody>
            </table>
            </div>
    </section>
    </body>

    {% endblock content %}