wds/tradingclosed/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import home
from tradingclosed import views
app_name="tradingclosed"

urlpatterns = [
    path('trading-closed/',views.closetemplate,name='trading-closed'),
    path('userlogin/',views.user_login,name='userlogin'),
    path('userlogout/',views.userlogout,name='userlogout'),
    path('news/',views.news,name='news'),
    path('',home,name="home"),

]

wds/wds/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('register/', core_views.register, name='register'),
    path('',include('core.urls',namespace='core')),
    #path('',include('international.urls',namespace='international'))
    #path('',include('tradingclosed.urls',namespace='tradingclosed')),
]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

wds/tradingclosed/models.py
from django.db import models

# Create your models here.

wds/tradingclosed/views.py
from django.conf import settings
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404,redirect
from django.views.generic import ListView, DetailView, View
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from  django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

def home(request):
    return render(request,"tradingclosed/home.html")

def closetemplate(request):
    return render(request,"tradingclosed/trading-closed.html")

def news(request):
    return render(request,"tradingclosed/news.html")
    
def user_login(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        print(username)
        print(password)


        user=authenticate(username=username,password=password)

        if user is not None:
                login(request,user)
        else:
            print("false login")
            messages.error(request, f'Invalid Teamname or Password')
            return redirect('tradingclosed:userlogin')
        return render(request,'tradingclosed/home.html')
    else:
        print("render part ran successfully")
        return render(request,'tradingclosed/userlogin.html')


@login_required
def userlogout(request):
    print("logout")
    logout(request)
    return redirect('/')

wds/tradingclosed/templates/tradingclosed/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<head>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Spectral+SC:ital,wght@0,700;1,500&display=swap');
        .para{
            font-family: 'Cardo', serif;
            font-size: 20px;
    
    color:white;
}
.head{

    font-family: 'Spectral SC', serif;
    color: white;
}
.portion{
    background-color: black;
}
.h2{
    font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
}
       
.btn-enter-wds{
    color: black;
    padding: 10px 25px;
    text-transform: uppercase;
    border-radius: 30px;
    border: none;
    background: #fcaf58d7;
    margin-bottom: 20px;
}
.btn-enter-wds:hover{
    background: #FCAF58;
}
        
.aboutUsBtn a{
    display: flex;

}

.btn-enter-wds-first{
    margin-top: 40px;
    
}



.rules-btn{
    margin: 0 auto;
    display: flex;
    flex-flow: row;
    margin-top: 5rem;
    width: 100%;
    position: relative;
}
.btn-rules-wds{
    color: black;
    padding: 10px 25px;
    text-transform: uppercase;
    border-radius: 30px;
    border: none;
    background: #fcaf58d7;
    margin: 0 auto;
    margin-top: -30px !important;
    margin-bottom: 20px;
}
.rules-1{
    margin-right: -50px;
}
.rules-2{
    margin-left: 90px;
}
.btn-rules-wds:hover{
    background: #FCAF58;
}

@media(max-width: 720px ) {
        .para{
            font-size: 12px;
        }
        
    }
    </style>
</head>
<body>
<header role="banner" class="position-absolute">
    <!-- Top Navigation -->
{% include "tradingclosed/navbar.html" %}
</header>
<!-- nav-carousel -->
<div class="carousel-default owl-carousel carousel-main carousel-nav-white nav-carosel-height">
    <div class="item">
        <div class="s-12 center">
            <!-- For ZOOM effect add classes "background-image-zoom-out" or "background-image-zoom-in" -->
            <div class="section text-center background-image-zoom-out">
                <!-- ZOOMED Carousel Image -->
                <div class="background-image background-image-object" style="background-image:url({% static 'images-2019/bg-11.jpg'%})"></div>
                <div class="background-image background-image-object" ></div>

                <div class="line" style="visibility: hidden;">
                    <hr class="animated-carousel-element break background-primary break-small break-center margin-top-130">
                    <p class="text-extra-thin animated-carousel-element text-white text-s-size-30 text-m-size-40 text-size-50 text-line-height-1 margin-bottom-0">
                        
                    </p>
                    <hr class="animated-carousel-element break background-primary break-small break-center">
                    <!-- <p class="animated-carousel-element slow text-white margin-top-40"></p> -->
                </div>
                <!-- Pie Charts -->
              
            </div>
        </div>
        <!-- white full width arrow object -->
        <img class="arrow-object" src="{% static 'img/arrow-object-white.svg'%}" alt="">
    </div>
</div>

<!-- Section 1 -->
<section class="portion section background-black text-center">
    <div class="line">
        <h1 class="head text text-size-50 text-m-size-40" style="color: #FCAF58;">
        Welcome to <b>WDS</b></h1>
        <p class="para">
            Money brings out the insecurity, fear and irrationality that we might otherwise keep hidden in polite society. Investing isn’t just a test of strategy– it’s a test of character, and what we do when investing is very often what we believe about ourselves. The Econ Club releases the teaser for their annual flagship event "Wolf of Dalal Street". Brush up your knowledge about domestic and international markets, and get ready to tackle the bull and the bear<br><br>
            Through this simulation of the stock market, you will learn how to analyze stocks, look for patterns that are in everyone's sight but observed by a few and then exploit it to optimise your profit and loss. <br>
            </p>
        {% if user.is_authenticated %}
        <a href="{% url 'tradingclosed:trading-closed' %}" class="s-12 m-6 l-3 center text-size-20 text-white btn-enter-wds btn-enter-wds-first">Enter WDS</a>
        {% else %}
        <a href="{% url 'tradingclosed:trading-closed' %}" class="s-12 m-6 l-3 center text-size-20  text-white btn-enter-wds btn-enter-wds-first">Enter WDS</a>
        {% endif %}

        <div class="rules-btn">
            <a href="https://drive.google.com/file/d/1U1O9yaAWVwK1XZc2LzHZ0roBRDJUXFXY/view" class="s-12 m-6 l-3 center text-size-20 text-white btn-rules-wds rules-1">Rulebook</a>
            <a href="https://drive.google.com/file/d/1Z1EcVPF6WvO-4BBe2uBpcvI1mSUTHm5Y/view?usp=sharing" class="s-12 m-6 l-3 center text-size-20 text-white btn-rules-wds rules-2">Schedule</a>
        </div>
        
    </div>
</section>

<!-- Section 2 -->
<section class="section" data-image-src="{% static 'images-2019/bg-5.jpg'%}">
    <div class="line">
        <div class="s-12 m-12 l-6">
            <h2 class="text-size-50" style="font-family: 'Spectral SC', serif; font-weight:600; color: #FCAF58;">
            Stock Market</h2>
            <h2 class="text-white" style="font-family: 'Spectral SC', serif; font-size: 1.5rem;
            ">
                What you will Gain from this event??</h2>
            <p class="margin-bottom" style="color:rgb(175, 175, 175)">You will learn how to convince others of why they should give what they have to you and take what you have for them, in simple words trade. But to change ones perspective on what you have to offer and mould it as per your opinions is like having an impact so huge and influencing power so strong that you really get to the other person. <br><br>
                Remember before selling or buying you have to sell your idea and vision to people around to really get around things the way you believe to be ideal.</p>
            
        </div>
    </div>
</section>


<section class="portion section-top-padding background-dark-hightlight aboutUsBtn" style="padding:50px">
    <div class="line">

        <!-- <a href="https://sites.google.com/view/econclub/about?authuser=0" class="s-12 m-6 l-3 center btn-enter-wds text-size-20 margin-bottom-90 text-white">About Us</a> -->
    </div>
</section>
</body>

{% include "footer.html" %}
{% endblock content %}

wds/tradingclosed/templates/tradingclosed/navbar.html
{% load static %}
<head>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Spectral+SC:ital,wght@0,700;1,500&display=swap');


    nav.fixed .logo-dark, .fixed nav .logo-dark {
    display: block;
    width: 100px;
    top: 10px;
}
    .top-nav a {
        font-family: 'Spectral SC', serif;
    }

</style>
</head>
        <nav class="background-transparent background-dark-dott full-width sticky">
            <!-- mobile version logo -->
            <div class="logo hide-l hide-xl hide-xxl">
                <a href="index.html" class="logo">
                    <!-- Logo Dark Version -->
                    <img class="logo-dark" src="{% static 'images-2019/WDS_Logo_Black.png'%}" alt="">
                </a>
            </div>
            <div class="top-nav">

                <!-- left menu items -->
                <div class="top-nav left-menu">
                    <ul class="right top-ul chevron">
                        <li class="active-item">
                        {% csrf_token %}
                        {% if user.is_staff %}
                        <a href="{% url 'admin:index' %}">&nbsp Admin </a>
                        {% endif %}
                        </li>
                        <li>
                            <a href="{% url 'tradingclosed:home' %}">Home</a>
                        </li>
                        <li>
                        
                        <a href="{% url 'tradingclosed:trading-closed' %}" style="font-family: 'Spectral SC', serif;">&nbsp Stocks</a>
                        
                        </li>
                       
                    </ul>
                </div>

                <!-- logo -->
                <ul class="logo-menu">
                    
                <a href="#" class="logo">
                
                        <!-- Logo White Version -->
                        <img class="logo-white" src="{% static 'images-2019/WDS_Logo_Black.png'%}" alt="">
                        <!-- Logo Dark Version -->
                        <img class="logo-dark" src="{% static 'images-2019/WDS_Logo_Black.png'%}" alt="">
                        
                    </a>
                </ul>
                
                <!-- right menu items -->
                <div class="top-nav right-menu">
                    <ul class="top-ul chevron">
                        
                        {% if user.is_authenticated %}
                        {% comment %}
                        <li><a href="{% url 'tradingclosed:trading-closed' %}">&nbsp News</a></li>
                        {% endcomment %}
                        <li><a href="{% url 'tradingclosed:news' %}">&nbsp News</a></li>
                       
                        <li><a href="{% url 'tradingclosed:trading-closed' %}">&nbsp Dashboard</a></li>
                        <li><a href="{% url 'tradingclosed:userlogout' %}">&nbsp Logout</a></li>
                        {% else %}
                        <li><a href="{% url 'tradingclosed:trading-closed' %}">&nbsp News</a></li>
                        <li><a href="{% url 'tradingclosed:userlogin' %}">&nbsp Login</a></li>
                        
                        {% endif %}
                        
                        
                                        
                    </ul>
                </div>
            </div>
        </nav>
        

wds/tradingclosed/templates/tradingclosed/news.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<style>
  body {
        background-image: url("{% static 'images-2019/bg-11.jpg' %}");
        background-attachment: fixed;
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
        font: 16px/1.6 Arial, sans-serif;
      }
.iframe-container{
  position: relative;
  width: 100%;
  padding-bottom: 56.25%; 
  height: 0;
  margin-bottom: 50px;
}
.iframe-container iframe{
  position: absolute;
  top:0;
  left: 0;
  width: 100%;
  height: 100%;
}
.cont1{
    width: 70%;
    height: 60%;
    
    margin: auto;
    
}
h1 {
    font-size:4rem;
    color: #FF8C42;
    font-weight: bold;
    margin-top: 15vh;
    margin-bottom: 10px;
    padding:10px;
    z-index: 1 !important;
}

.bg{
    text-align: center;
    background-color: rgba(0, 0, 0, 0.7);
    height:90vh;
   
    margin-bottom: 100px;
}
.bg p{
    color: white !important;
    font-family:Verdana, Geneva, Tahoma, sans-serif;
    margin-bottom: 20px !important;
    width:60%;
    margin:auto;
    font-size: 1.5rem;
    line-height: 1.1;
}
.card{
    background-color: #FCAF58 !important;
}

@media screen and (max-width:1120px) {
    h1{
    margin-top: 9vh;
}
.bg{
    height:75vh;
    margin-bottom: 80px;
}
.bg p{
    font-size: 1.5rem;
    width:80%;
}
.iframe-container{
    margin-bottom: 5px;
    height:60%;
    width:95%;
    
}
.cont{
    width:85%;
}
}
@media screen and (max-width:768px) {
    h1{
    margin-top: 4vh;
}
.bg{
    height:55vh;
    margin-bottom: 80px;
}
.bg p{
    font-size: 1.5rem;
    width:80%;
}
.iframe-container{
    margin-bottom: 5px;
    height:90%;
    width:100%;
    
}
.cont{
    width:90%;
}
}
@media screen and (max-width:480px) {
h1{
    margin-top: 8vh;
}
.bg{
    height:60vh;
    margin-bottom: 80px;
}
.bg p{
    font-size: 1rem;
    width:80%;
}
.iframe-container{
    margin-bottom: 5px;
    height:90%;
    width:100%;
    
}
.cont{
    width:90%;
}
}
</style>



<body>

        <!-- Top Navigation -->
    {% include "tradingclosed/navbar.html" %}
    </header>
    <div class="container bg">
        <h1>NEWS</h1>
       
                <p class="card-text">Stock Market is not all about trading.How well you understand your surroundings will decide whether you gain or lose.So watch the NEWS carefully!</p>

    
        <div class="cont1">
            
            <div class="iframe-container">
                <img style="height:700; width:1200" src="https://drive.google.com/file/d/1Z1EcVPF6WvO-4BBe2uBpcvI1mSUTHm5Y/view?usp=sharing"></img></div>
        </div>
    </div>
{% include "footer.html" %}
</body>



{%endblock%}

wds/tradingclosed/templates/tradingclosed/trading-closed.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link href="https://fonts.googleapis.com/css?family=Teko:700&display=swap" rel="stylesheet">

    <title>
        Trading closed
    </title>

<style>


body {
    background-image: url("{% static './images-2019/close6.jpg'%}");
    background-attachment: fixed;
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
    color: #4dbc56;
    margin: auto;
    display: grid;
    grid-template-columns: 1fr;
    grid-template-rows: 1fr;
    align-items: center;
    justify-items: center;
}
    h1 {
    margin:0;
    padding-bottom: 6rem;
    grid-column: 1;
    grid-row: 1;
    z-index: 1;
    font-family: 'Teko', sans-serif;
    font-size: 10rem;
    text-transform: uppercase;
    animation: glow 2s ease-in-out infinite alternate;
    text-align: center;
  }
.container{
    margin-top: 200px;
}
  @keyframes glow {
    from {
      text-shadow: 0 0 20px #2da96f;
    }
    to {
      text-shadow: 0 0 30px #34c17f, 0 0 10px #4dc79e;
    }
  }

</style>
    <body>
        <div class="container">
            <h1><span class='one'>t</span><span class='two'>r</span><span class='three'>a</span><span class='four'>d</span><span class='five'>i</span><span class='six'>n</span><span class='six'>g</span> <span class='six'>c</span><span class='six'>l</span><span class='six'>o</span><span class='six'>s</span><span class='six'>e</span><span class='six'>d</span></h1>

        </div>

    </body>

</html>

wds/tradingclosed/templates/tradingclosed/userlogin.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block usrlgn %}

<style>
  @import url('http://fonts.googleapis.com/css?family=Open+Sans:400,700');
*{
	padding:0;
	margin:0;
}

body{
    background-image: url("{% static 'images-2019/bg-11.jpg' %}");
    background-attachment: fixed;
    background-position: center;
    background-repeat: no-repeat;
	background-size: cover;
    font:16px/1.6 Arial,  sans-serif;
}

.background-transparent {
    background: none;
    border: none;
    box-shadow: none;
}

.top-nav ul li a{
    color: #fff;
    font-size: 1.35rem;
}
.form-field{
  height:3.5rem !important;
}
.btn {
  background-color: #FCAF58;
}
.main-form{
  box-shadow: 2px 10px 40px rgba(224, 137, 74,0.5);
}

.form-heading h2{
  font-size: 2.5rem;
  font-family: 'Spectral SC', serif;
  
}

form button{
            color: black;
            padding: 10px 25px;
            text-transform: uppercase;
            border-radius: 15px;
            border: none;
            background:#FCAF58;
        }
        form button:hover{
            background: #fcaf58bb;
        }
        form button:active{
            background: #FCAF58;
            
        }



</style>









<body>
      <!--    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="Username">username</label>
                <input type="text" class="form-control"  placeholder="Enter user name" name="username">
              </div>
              <div class="form-group">
                <label for="Password">Password</label>
                <input type="password" class="form-control" name="password" placeholder="Password">
              </div>
              <div class="form-group">
              <button type="submit" class="btn btn-primary">Submit</button>
              </div>
        </form>
    </div>

  -->
    <!-- HEADER -->
    <header role="banner" class="position-absolute">
  {% include "tradingclosed/navbar.html" %}

    </header>
  <section>

    <div class="container-fluid col-xl-5" style="padding:7px; ">

      <div class="row main-form">

          <div class="form-heading">
              <h2>Log In to WDS</h2>
          </div>
          
          <form class="col s12" method="POST">
            {% csrf_token %}
          <div class="row">
              <div class="input-field col s12 form-field">
                  <input  id="first_name" type="text" class="validate form-field"  name="username">
                  <label for="Username">User Name</label>
              </div>
          </div>


          <div class="row">
              <div class="input-field col s12 form-field">
                  <input id="password" type="password" class="validate form-field" name="password">
                  <label for="Password">Password</label>
              </div>
          </div>
          
                          
          <button class="" type="submit" name="action">Login
              <i class="material-icons right"></i>
          </button>
          </form>
      </div>
    </div>
  </section>
  
</body>
{% endblock usrlgn %}